### ISSUE TITLE
Invalid cross-device link (os error 18)

### ISSUE THREAD

**Issue by 0x6d6c** [devmatteini/dra#121]
Hi!
There is an issue when the installed assets should be moved from the OS `/tmp` location to the destination path.
In my case the `/tmp` directory is on `ext4` partition and my home `/home` directory is encrypted with LUKS, so the error is obvious here.
Maybe an additional flag like `dra download --tmpdir=<dir> --output=<destinationPath>` could solve the problem.

**Comment by devmatteini** [comment]
Hi @0x6d6c and thanks for checking out `dra`!

The idea you suggested seems good, but I'll try something else to make it work out of the box without specifying any flag.

I'll post an update when I'll get something working!

**Comment by devmatteini** [comment]
Hi @0x6d6c, you can download the latest release [0.4.7](https://github.com/devmatteini/dra/releases/tag/0.4.7) and this problem should be fixed!

**Comment by 0x6d6c** [comment]
Hi @devmatteini. I have downloaded the new 0.4.7 release – the issue has been solved and I like your solution – copying files instead of moving them makes sense – the tmp files will be destroyed anyway on reboot.
Thank you for your work!

**Comment by devmatteini** [comment]
Glad it works!
