### ISSUE TITLE
Trojan:Script/Wacatac.B!ml 

### ISSUE THREAD

**Issue by geri777** [devmatteini/dra#190]
Microsoft defender on Windows 10 pro has detected dra.exe as a trojan. 
virustotal.com has 0/72 findings - so seems to be safe(?)

**Comment by devmatteini** [comment]
Hi @geri777 and thanks for trying out `dra`!

I did run Windows Defender, but it didn't detect `dra.exe` as a trojan.

Of course `dra` is safe to use, probably it's just a false positive. There are some `dra` Windows users, but this is the first time it has happened.

If you don't feel safe enough, you can read the source code in this repository and check the [GitHub Actions CI/CD](https://github.com/devmatteini/dra/blob/main/.github/workflows/release.yml) to see how `dra.exe` is built and released.

If you have any other questions, let me know!
