### ISSUE TITLE
Error: automatic download of asset

### ISSUE THREAD

**Issue by rgarrigue** [devmatteini/dra#191]
## dra version
0.5.2

## Bug report
Repository: flosell/iam-policy-json-to-terraform
Release: 1.8.2
OS: linux
ARCH: x86_64

Hello. The above repository got the relevant bin named amd64, maybe you can match it automatically ?

**Comment by devmatteini** [comment]
I thought about this and decided that the current implementation is fine.
We shouldn't handle every edge case for non-standard names.
