### ISSUE TITLE
Error: automatic download of asset

### ISSUE THREAD

**Issue by plutonium-239** [devmatteini/dra#224]
## dra version
0.6.1
## Bug report
Repository: zyedidia/micro
Release: v2.0.14
OS: windows
ARCH: x86_64

There are windows x64 versions available:
![image](https://github.com/user-attachments/assets/ecd5a3ef-0fec-4173-b99b-d5bf7c49b420)

**Comment by devmatteini** [comment]
Hi! You can download [0.6.2](https://github.com/devmatteini/dra/releases/tag/0.6.2) version with the bug fixed.

Thank you for your report!
