### ISSUE TITLE
[Question]What is the direct download URL for latest dra deb package that is not version dependent ?

### ISSUE THREAD

**Issue by sebma** [devmatteini/dra#225]
Hi,

I came up with this URL to download the latest version of `dra` but it is version dependent : https://github.com/devmatteini/dra/releases/latest/download/dra_0.6.2-1_amd64.deb

Is there an URL to direct download URL for latest dra deb package that is not version dependent ?

**Comment by devmatteini** [comment]
Hi @sebma! 

Every release asset have the version in the filename.

May I ask you what you are trying to do, so I can try to help you?

If you want to automate the first installation of dra, I currently use this [bash script](https://github.com/devmatteini/dotfiles/blob/f9c9aa944382cd3837a586b12035a4ee07c5d92a/bootstrap/dependencies.sh#L19C1-L23C28).
To download the Debian package, you can modify it like so:
```bash
TMP_DIR=$(mktemp --directory)
DRA_DEB="$TMP_DIR/dra.deb"

curl -s https://api.github.com/repos/devmatteini/dra/releases/latest \
| grep "browser_download_url.*amd64.deb" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -O "$DRA_DEB" -i -

sudo dpkg -i "$DRA_DEB"
``` 

If you have dra already installed, you can use dra itself to download and install the latest version:
```bash
sudo dra download -s "dra_{tag}-1_amd64.deb" -i devmatteini/dra
```

**Comment by sebma** [comment]
@devmatteini Thanks 😄 
> ```
> sudo dra download -s "dra_{tag}-1_amd64.deb" -i devmatteini/dra
> ```

What is the `{tag}` meaning in your last line ?

**Comment by devmatteini** [comment]
The `{tag}` is the placeholder part of the untagged asset that is generated by `dra untag` subcommand.

You can read how it works here: https://github.com/devmatteini/dra#selection

Hope this helps :smile:
