### ISSUE TITLE
Unable to install binary file from tar.gz if the executable is inside subfolder

### ISSUE THREAD

**Issue by MRDGH2821** [devmatteini/dra#232]
I'm using dra inside chezmoi to install some packages.
One of which is [Ludusavi](https://github.com/mtkennerly/ludusavi)

Now my issue is that dra is not able to install binary executable from ludusavi archive file.

Here is the command:
```shell
dra download -o "$HOME"/.local/bin/ mtkennerly/ludusavi --select ludusavi-v{tag}-linux.zip --install-file ludusavi
```

I even tried `ludusavi/ludusavi` but it fails still saying that executable not found.

I manually downloaded & found out that the executable is inside a subfolder.

Is there anything wrong I'm doing?

**Comment by devmatteini** [comment]
Hi @MRDGH2821!

Your command is correct. One suggestion is to use `--install` instead of `--install-file` which is not required in this case ([docs](https://github.com/devmatteini/dra#install-assets)).

The issue you are getting the error `No executable found` is because there are no executable files inside the zip file.
The only file `ludusavi` has permission 0644. That's why `dra` thinks there are no executables.

You should ask the maintainers of [mtkennerly/ludusavi](https://github.com/mtkennerly/ludusavi) to fix the issue and keep the file permissions.

Hope this helps :smile: 

PS: May I ask you how you found out about `dra`?

**Comment by MRDGH2821** [comment]
> Your command is correct. One suggestion is to use `--install` instead of `--install-file` which is not required in this case ([docs](https://github.com/devmatteini/dra#install-assets)).

I was using `--install` but I got an error so I used `--install-file` assuming that this option will point out to the file.

> The issue you are getting the error `No executable found` is because there are no executable files inside the zip file.
> The only file `ludusavi` has permission 0644. That's why `dra` thinks there are no executables.

What should be the correct permissions then?

> You should ask the maintainers of [mtkennerly/ludusavi](https://github.com/mtkennerly/ludusavi) to fix the issue and keep the file permissions.

Done - https://github.com/mtkennerly/ludusavi/issues/398


> PS: May I ask you how you found out about `dra`?  

I have a [dotfiles](https://github.com/MRDGH2821/dotfiles) repo managed using Chezmoi. 
I also use it to install packages. Some of them are github releases & earlier I was hard coding direct links. If the release got updated, I would have an older version installed.

So I started searching on how to auto download GitHub releases. And came across dra!

Now guaranteed to get latest release everytime I restore my dotfiles.

**Comment by devmatteini** [comment]
> I was using --install but I got an error so I used --install-file assuming that this option will point out to the file.

When the error is `No executable found` neither of the flags will work.
Generally speaking, you will get a specific error that tells you to use `--install-file` instead. You can try to run this command:
```shell
dra download -s helloworld-many-executables-unix.tar.gz -i devmatteini/dra-tests
```

> What should be the correct permissions then?

Executable files on Linux should have 0775

> I have a [dotfiles](https://github.com/MRDGH2821/dotfiles) repo managed using Chezmoi [...]

That's great! I developed `dra` for the same reason :smile:

**Comment by devmatteini** [comment]
As a workaround while the upstream repository fix the issue, you can run these commands:
```shell
dra download -s ludusavi-v{tag}-linux.zip -o ludusavi.zip mtkennerly/ludusavi
unzip ludusavi.zip
chmod +x ludusavi
mv ludusavi "$HOME"/.local/bin/
```

**Comment by MRDGH2821** [comment]
Thanks for the work around!

There's an update from upstream too:
https://github.com/mtkennerly/ludusavi/issues/398#issuecomment-2403926697

So they will be fixing it in next release.
