### ISSUE TITLE
Feature: choose where to install

### ISSUE THREAD

**Issue by rgarrigue** [devmatteini/dra#233]
Hello

In some specific case like an asset with a single executable, I wish I could straight away send it to /usr/local/bin, like `dra download -a -i  --install-dir /usr/local/bin whatever/test`.

Could even add an option to remove any suffix looking like -<semver>

This little thing would be the missing bit to have one line command to install the many golang / rust & co tooling available on github :-)

**Comment by devmatteini** [comment]
Hi @rgarrigue!

You can already do this using the `-o/--output` option:
```shell
dra download -a -i  -o /usr/local/bin whatever/test
```

This will install whatever you download to `/usr/local/bin`.

> Could even add an option to remove any suffix looking like -

If you want to change the executable name, you can use `-o` again:
```shell
dra download -a -i  -o /usr/local/bin/mytestcli whatever/test
```

There are more examples here https://github.com/devmatteini/dra#examples
