### ISSUE TITLE
why can't dra download FreeTube?

### ISSUE THREAD

**Issue by candrapersada** [devmatteini/dra#242]
why `dra download FreeTubeApp/FreeTube` `Error fetching release: Repository or release not found`
https://github.com/FreeTubeApp/FreeTube/releases
https://github.com/FreeTubeApp/FreeTube/releases/download/v0.22.0-beta/freetube-0.22.0-win-x64-portable.7z

**Comment by devmatteini** [comment]
Hi! Currently you can't download latest pre-releases. It's something I might add in the future.

For the time you can add the `--tag v0.22.0-beta` to your download command.

**Comment by candrapersada** [comment]
and why `dra download --select "PortableGit-{tag}-64-bit.7z.exe" git-for-windows/git` Release tag is v2.47.0.windows.2
`No asset found for PortableGit-{tag}-64-bit.7z.exe`
https://github.com/git-for-windows/git/releases/download/v2.47.0.windows.2/PortableGit-2.47.0.2-64-bit.7z.exe

**Comment by devmatteini** [comment]
It doesn't work because the tag `v2.47.0.windows.2` is not part of the asset name `PortableGit-2.47.0.2-64-bit.7z.exe`

**Comment by candrapersada** [comment]
> It doesn't work because the tag `v2.47.0.windows.2` is not part of the asset name `PortableGit-2.47.0.2-64-bit.7z.exe`

how to download the latest version of git without using the version number?

**Comment by devmatteini** [comment]
Unfortunately it seems you can't. You have to run `dra download --select "PortableGit-2.47.0.2-64-bit.7z.exe" git-for-windows/git`
