### ISSUE TITLE
--copy flag

### ISSUE THREAD

**Issue by akimdi** [devmatteini/dra#90]
Hello. Is it possible to make a --copy flag. Like here?
https://github.com/timvisee/ffsend/commit/b697bc3231c840ace80ab3f0343cee9591b07837

Then you could do it like this
```
dra --copy untag bcicen/ctop
```

**Comment by devmatteini** [comment]
Hi and thanks for checking out `dra`!

I like the idea and will try to implement it.
Seems that the crate used by `timvisee/ffsend` is not maintained anymore, but I found this one: [arboard](https://crates.io/crates/arboard).

**Comment by devmatteini** [comment]
It turned it was pretty easy to implement!

If you download the [latest release 0.4.3](https://github.com/devmatteini/dra/releases/tag/0.4.3) you can already try it!
You can read the [docs](https://github.com/devmatteini/dra/tree/0.4.3#non-interactive) on how to use it.

**Comment by devmatteini** [comment]
Strange...I've tested it on two different machines and works fine on both Wayland and X11.

Can you paste the error message?
What distribution and display server are you using?

**Comment by devmatteini** [comment]
Ok thanks! I'll investigate why this happens

**Comment by devmatteini** [comment]
Hi @akimdi, I've installed archlinux (with Gnome) on a VM and the `--copy` works fine with both X11 and Wayland.
What DE are you using?

**Comment by devmatteini** [comment]
Hi! I decided to remove this feature since I couldn't find a solution that worked reliably everywhere.
